[package]
name = "nocontrol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap="0.7.0"
clap="3.0.0-beta.5"
